tnt:
  power: -3.6
  min-y: 1.0
  recharge: 10

jetpack:
  y: 3.6
  recharge: 60

arena-spawns: {}

blocks:
  crack-start-after: 6
  remove-after: 12

database:
  host: "127.0.0.1"
  port: 3306
  name: "madness"
  username: "root"
  password: "password"