name: Madness
version: 1.0
main: fr.europixel.madness.MadnessPlugin
author: zozoclem
softdepend:
  - Vault

commands:
  madness:
    description: Commande principale de Madness
    usage: /madness reload|setpos1|setpos2
  setspawn:
    description: Definit le spawn du lobby
    usage: /setspawn
  setarenaspawn:
    description: Ajoute un spawn de l'arene
    usage: /setarenaspawn

permissions:
  madness.reload:
    description: Permet de recharger Madness
    default: op
  madness.admin:
    description: Permet d'utiliser les commandes admin
    default: op
  madness.coins.multiplier.1_5:
    description: Multiplicateur de coins x1.5
    default: false
  madness.coins.multiplier.2:
    description: Multiplicateur de coins x2
    default: false
  madness.coins.multiplier.3:
    description: Multiplicateur de coins x3
    default: false